Updated build script
* Build script will check for wiringPi and install if missing
* Build script now shows user how to connect the OPL2 board
* Build script allows user to test OPL2 board after installation
* Added connecting.sh script to show how to connect the OPL2 board
* Modified OPL2.h by removing unnecessary ORANGE_PI board type

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,46 +1,93 @@
 #!/bin/sh
 
-echo "*** OPL2 Audio Board build script ***"
-echo ""
-
 if [ "$(id -u)" != "0" ]
   then echo "Please run as root"
   exit
 fi
 
-if [ "$1" = "-opi" ]
+clear
+echo "\033[1;33m                          ________ __________.____    ________  "
+echo "\033[1;33m                          \\_____  \\\\______    \\    |   \\_____  \\ "
+echo "\033[1;32m                           /   |   \\|     ___/    |    /  ____/ "
+echo "\033[1;36m                          /    |    \\    |   |    |___/       \\ "
+echo "\033[1;34m                          \\_______  /____|   |_______ \\_______ \\"
+echo "\033[1;33m      _____            .___.__    \033[1;34m\\/\033[1;33m   __________    \033[1;34m\\/       \\/\033[1;33m        .___ "
+echo "\033[1;33m     /  _  \\  __ __  __| _/|__| ____   \\______   \\ _________ _______  __| _/"
+echo "\033[1;32m    /  /_\\  \\|  |  \\/ __ | |  |/  _ \\   |    |  _//  _ \\__  \\\\_   __ \\/ __ | "
+echo "\033[1;36m   /    |    \\  |  / /_/ | |  (  (_) )  |    |   (  (_) ) __ \\|  | \\/ /_/ | "
+echo "\033[1;34m   \\____|__  /____/\\____ | |__|\\____/   |______  /\\____(____  /__|  \\____ | "
+echo "\033[1;34m           \\/           \\/                     \\/           \\/           \\/ \033[0m"
+echo "Installation script for Raspberry Pi and compatibles"
+echo "Library version 1.4.0, 3rd March 2018"
+echo "Copyright (c) 2016-2018 Maarten Janssen, Cheerful"
+echo ""
+
+echo -n "Checking for WiringPi... "
+if ! type "gpio" > /dev/null
 then
-	sed -i 's/^\s*#define BOARD_TYPE.*/\t#define BOARD_TYPE ORANGE_PI/' src/OPL2.h
-	echo "Board type set to Orange Pi."
-else
-	sed -i 's/^\s*#define BOARD_TYPE.*/\t#define BOARD_TYPE RASPBERRY_PI/' src/OPL2.h
-	if [ "$1" = "-rpi" ]
+	echo "\033[0;31mFailed\033[0m"
+	echo -n "\nWiringPi was not found. Do you want to install it now? "
+	read REPLY
+	REPLY=$(echo "$REPLY" | awk '{gsub(/ /, "", $0); print toupper(substr($0==""?"N":$0, 1, 1))}')
+
+	if [ $REPLY = "Y" ]
 	then
-		echo "Board type set to Raspberry Pi."
+		echo -n "Downloading and installing WiringPi... "
+		apt-get install -y git-core > /dev/null
+		rm -rf temp
+		mkdir temp
+		cd temp
+		git clone --quiet git://git.drogon.net/wiringPi > /dev/null
+		cd wiringPi
+		#./build > /dev/null
+		cd ../..
+		rm -rf temp
+	
+		# Check if WiringPi installed ok...
+		if ! type "gpio" > /dev/null; then
+			echo "\033[0;31mFailed\033[0m"
+			echo "WiringPi installation failed! Sorry mate, you're on your own."
+			echo ""
+			exit
+		fi	
+		echo "\033[0;32mDone\033[0m"
 	else
-		echo "Board type not set! Going with Raspberry Pi as default."
-		echo "To set board type use:"
-		echo "  $ ./build -rpi  - Raspberry Pi"
-		echo "  $ ./build -opi  - Orange Pi"
-		echo ""
-		echo "Press ^c now if you want to stop compiling!"
-		sleep 10
+		echo "OPL2 Audio Board installation cannot continue without WiringPi."
+		exit
 	fi
+else
+	echo "\033[0;32mOk\033[0m"
 fi
 
-echo ""
-echo "Building the OPL2 library..."
+
+echo -n "Building the OPL2 library... "
+sed -i 's/^\s*#define BOARD_TYPE.*/\t#define BOARD_TYPE RASPBERRY_PI/' src/OPL2.h
 gcc -std=c++11 -c -fPIC src/OPL2.cpp -lwiringPi
 gcc -shared -o libOPL2.so OPL2.o
 mv libOPL2.so /usr/lib/
 cp src/OPL2.h /usr/include/
 rm OPL2.o
 ldconfig
+echo "\033[0;32mDone\033[0m"
 
-echo "Compiling examples..."
+echo -n "Compiling examples... "
 gcc -std=c++11 -Wall -o examples_pi/demotune/demotune examples_pi/demotune/demotune.cpp -lOPL2 -lwiringPi
 gcc -std=c++11 -Wall -o examples_pi/drums/drums examples_pi/drums/drums.cpp -lOPL2 -lwiringPi
 gcc -std=c++11 -Wall -o examples_pi/simpletone/simpletone examples_pi/simpletone/simpletone.cpp -lOPL2 -lwiringPi
 gcc -std=c++11 -Wall -o examples_pi/opl2play/opl2play examples_pi/opl2play/opl2play.cpp -lOPL2 -lwiringPi -lz
-echo "Done."
+echo "\033[0;32mDone\033[0m"
+echo "Installation complete."
+
 echo ""
+./connecting.sh
+
+echo -n "Are you ready to try your OPL2 Audio Board? "
+read REPLY
+REPLY=$(echo "$REPLY" | awk '{gsub(/ /, "", $0); print toupper(substr($0==""?"N":$0, 1, 1))}')
+if [ $REPLY = "Y" ]
+then
+	echo "If all went successful you should hear music playing now!"
+	./examples_pi/demotune/demotune &
+fi
+echo ""
+
