Updates for release 1.4.7
In this release:
* The Raspberry Pi / Orange Pi build script has been updated so it can
also be run from a absolute path.
* The build script requires no parameters, documentation is updates.
* DosBoxPassthrough sketch is renamed to SerialPassthrough sice it has
more uses now.
* [OPL3BankEditor](https://github.com/Wohlstand/OPL3BankEditor) by
Wohlstand now supports the OPL2 Board using the SerialPassthrough.
* Removed SerialIface sketch to prevent confusion and have a single
simple serial interface.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -18,92 +18,85 @@ echo "\033[1;36m   /    |    \\  |  / /_/ | |  ( /_/ )  |    |   ( /_/ ) __ \\| 
 echo "\033[1;34m   \\____|__  /____/\\____ | |__|\\___/   |______  /\\___(____  /__|  \\____ | "
 echo "\033[1;34m           \\/           \\/                    \\/          \\/           \\/ \033[0m"
 echo "Installation script for Raspberry Pi and compatibles"
-echo "Library version 1.4.6, 17th of June 2019"
+echo "Library version 1.4.7, 3rd of September 2019"
 echo "Copyright (c) 2016-2019 Maarten Janssen, Cheerful"
 echo ""
+
+MYDIR="${0%/*}"
 
 echo -n "Checking for SPI devices... "
 if [ "$(ls /dev/*spi* 2>/dev/null)" != "" ]
 then
-	echo "\033[0;32mOk\033[0m"
+        echo "\033[0;32mOk\033[0m"
 else
-	echo "\033[0;31mFailed\033[0m"
-	echo "\nNo SPI devices were found enabled on your Pi."
-	echo "Please run '\033[1;34msudo raspi-config\033[0m' and enable SPI from the 'Interfacing Options'"
-	echo "menu. If you are using a different board then please consult its documentation"
-	echo "on how to enable SPI on your board."
-	echo ""
-	exit
+        echo "\033[0;31mFailed\033[0m"
+        echo "\nNo SPI devices were found enabled on your Pi."
+        echo "Please run '\033[1;34msudo raspi-config\033[0m' and enable SPI from the 'Interfacing Options'"
+        echo "menu. If you are using a different board then please consult its documentation"
+        echo "on how to enable SPI on your board."
+        echo ""
+        exit
 fi
 
 echo -n "Checking for WiringPi... "
 if ! type "gpio" > /dev/null
 then
-	echo "\033[0;31mFailed\033[0m"
-	echo "\nWiringPi was not found."
-	echo -n "Do you want to download and install it now? "
-	read REPLY
-	REPLY=$(echo "$REPLY" | awk '{gsub(/ /, "", $0); print toupper(substr($0==""?"N":$0, 1, 1))}')
+        echo "\033[0;31mFailed\033[0m"
+        echo "\nWiringPi was not found."
+        echo -n "Do you want to download and install it now? "
+        read REPLY
+        REPLY=$(echo "$REPLY" | awk '{gsub(/ /, "", $0); print toupper(substr($0==""?"N":$0, 1, 1))}')
 
-	if [ $REPLY = "Y" ]
-	then
-		echo -n "Downloading and installing WiringPi... "
-		apt-get install -y git-core > /dev/null
-		rm -rf opl2_temp
-		mkdir opl2_temp
-		cd opl2_temp
-		git clone --quiet git://git.drogon.net/wiringPi > /dev/null
-		cd wiringPi
-		./build > /dev/null
-		cd ../..
-		rm -rf opl2_temp
+        if [ $REPLY = "Y" ]
+        then
+                echo -n "Downloading and installing WiringPi... "
+                apt-get install -y wiringpi > /dev/null
 
-		# Check if WiringPi installed ok...
-		if ! type "gpio" > /dev/null; then
-			echo "\033[0;31mFailed\033[0m"
-			echo "WiringPi installation failed! Sorry mate, you're on your own."
-			echo ""
-			exit
-		fi
-		echo "\033[0;32mDone\033[0m"
-	else
-		echo "OPL2 Audio Board installation cannot continue without WiringPi."
-		echo ""
-		exit
-	fi
+                # Check if WiringPi installed ok...
+                if ! type "gpio" > /dev/null; then
+                        echo "\033[0;31mFailed\033[0m"
+                        echo "WiringPi installation failed! Sorry mate, you're on your own."
+                        echo ""
+                        exit
+                fi
+                echo "\033[0;32mDone\033[0m"
+        else
+                echo "OPL2 Audio Board installation cannot continue without WiringPi."
+                echo ""
+                exit
+        fi
 else
-	echo "\033[0;32mOk\033[0m"
+        echo "\033[0;32mOk\033[0m"
 fi
 
 echo -n "Building the OPL2 library... "
-sed -i 's/^\s*#define BOARD_TYPE.*/\t#define BOARD_TYPE OPL2_BOARD_TYPE_RASPBERRY_PI/' src/OPL2.h
-gcc -std=c++11 -c -fPIC src/OPL2.cpp -lwiringPi
-gcc -shared -o libOPL2.so OPL2.o
-mv libOPL2.so /usr/lib/
-cp src/OPL2.h /usr/include/
-rm OPL2.o
+sed -i 's/^\s*#define BOARD_TYPE.*/\t#define BOARD_TYPE OPL2_BOARD_TYPE_RASPBERRY_PI/' "$MYDIR"/src/OPL2.h
+gcc -std=c++11 -c -fPIC -o "$MYDIR"/OPL2.o "$MYDIR"/src/OPL2.cpp -lwiringPi
+gcc -shared -o "$MYDIR"/libOPL2.so "$MYDIR"/OPL2.o
+mv "$MYDIR"/libOPL2.so /usr/lib/
+cp "$MYDIR"/src/OPL2.h /usr/include/
+rm "$MYDIR"/OPL2.o
 ldconfig
 echo "\033[0;32mDone\033[0m"
 
 echo -n "Compiling examples... "
-gcc -std=c++11 -Wall -o examples_pi/demotune/demotune examples_pi/demotune/demotune.cpp -lOPL2 -lwiringPi
-gcc -std=c++11 -Wall -o examples_pi/drums/drums examples_pi/drums/drums.cpp -lOPL2 -lwiringPi
-gcc -std=c++11 -Wall -o examples_pi/simpletone/simpletone examples_pi/simpletone/simpletone.cpp -lOPL2 -lwiringPi
-gcc -std=c++11 -Wall -o examples_pi/opl2play/opl2play examples_pi/opl2play/opl2play.cpp -lOPL2 -lwiringPi -lz
-gcc -std=c++11 -Wall -o examples_pi/frequency_sweep/sweep examples_pi/frequency_sweep/sweep.cpp -lOPL2 -lwiringPi -lz
+gcc -std=c++11 -Wall -o "$MYDIR"/examples_pi/demotune/demotune "$MYDIR"/examples_pi/demotune/demotune.cpp -lOPL2 -lwiringPi
+gcc -std=c++11 -Wall -o "$MYDIR"/examples_pi/drums/drums "$MYDIR"/examples_pi/drums/drums.cpp -lOPL2 -lwiringPi
+gcc -std=c++11 -Wall -o "$MYDIR"/examples_pi/simpletone/simpletone "$MYDIR"/examples_pi/simpletone/simpletone.cpp -lOPL2 -lwiringPi
+gcc -std=c++11 -Wall -o "$MYDIR"/examples_pi/opl2play/opl2play "$MYDIR"/examples_pi/opl2play/opl2play.cpp -lOPL2 -lwiringPi -lz
+gcc -std=c++11 -Wall -o "$MYDIR"/examples_pi/frequency_sweep/sweep "$MYDIR"/examples_pi/frequency_sweep/sweep.cpp -lOPL2 -lwiringPi -lz
 echo "\033[0;32mDone\033[0m"
 echo "Installation complete."
 
 echo ""
-./connecting
+"$MYDIR"/connecting
 
 echo -n "Are you ready to try your OPL2 Audio Board? "
 read REPLY
 REPLY=$(echo "$REPLY" | awk '{gsub(/ /, "", $0); print toupper(substr($0==""?"N":$0, 1, 1))}')
 if [ $REPLY = "Y" ]
 then
-	echo "If all went successful you should hear music playing now!"
-	./examples_pi/demotune/demotune &
+        echo "If all went successful you should hear music playing now!"
+        "$MYDIR"/examples_pi/demotune/demotune &
 fi
 echo ""
-
